name: DevSecOps IaC Pipeline

on: [push]

jobs:
  iac-security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # -------------------------------
      # 1. Validación CloudFormation
      # -------------------------------
      - name: Validate CloudFormation templates
        run: |
          for file in templates/*.yml; do
            echo "Validating $file"
            aws cloudformation validate-template --template-body file://$file || exit 1
          done
        env:
          AWS_DEFAULT_REGION: us-east-1

      # -------------------------------
      # 2. cfn-nag (Docker)
      # -------------------------------
      - name: Run cfn-nag
        run: |
          docker run --rm -v ${{ github.workspace }}:/data \
          stelligent/cfn_nag \
          cfn_nag_scan --input-path /data/templates --fail-on-warnings

      # -------------------------------
      # 3. Checkov (IaC scanning)
      # -------------------------------
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: templates
          framework: cloudformation
          soft_fail: false

      # -------------------------------
      # 4. Trivy (misconfig + secrets)
      # -------------------------------
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          scan-ref: templates/
          exit-code: 1