name: Cloudformation nag
on: [push]
# on:
#   pull-request_target:
#     branches:
#       - main

jobs:
  cloudformation-nag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: | # usar varios scripts en la misma sesión
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" # Activar brew en la máquina de ubuntu
          brew install ruby brew-gem 
          brew gem install cfn-nag